# -*- coding: utf-8 -*-
"""Day 6n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oS1DhBEyamLu2fysJtNb3_79zJo_PW5
"""

# Patterns

# ****
# ****
# ****
# ****

for i in range(1,5):
  for j in range(1,5):
    print('*',end=" ")
  print("")

# 1111
# 2222
# 3333
# 4444

for i in range(1,5):
  for j in range(1,5):
    print(i,end=" ")
  print("")

# 1234
# 1234
# 1234
# 1234

for i in range(1,5):
  for j in range(1,5):
    print(j,end=" ")
  print("")

# 44444
# 33333
# 22222
# 11111

for i in range(4,0,-1):
  for j in range(5,0,-1):
    print(i,end=" ")
  print("")

# 12345
# 678910
# 1112131415
# 1617181920

count=1
for i in range(1,5):
  for j in range(0,5):
    print(count,end=" ")
    count+=1
  print("")

# 46810
# 46810
# 46810
# 46810

for i in range(1,5):
  count=2
  for j in range(1,5):
    print(count*2,end=" ")
    count+=1
  print("")

# 1
# 12
# 123
# 1234

for i in range(1,5):
  for j in range(1,i+1):
    print(j,end=" ")
  print("")

# *
# **
# ***
# ****

for i in range(1,5):
  for j in range(1,i+1):
    print('*',end=" ")
  print("")

# 4
# 43
# 432
# 4321

for i in range(4,0,-1):
  for j in range(4,i-1,-1):
    print(j,end=" ")
  print("")

# 4321
# 432
# 43
# 4

for i in range(1,5):
  for j in range(4,i-1,-1):
    print(j,end=" ")
  print("")

# 1234
# 123
# 12
# 1

for i in range(4,0,-1):
  for j in range(1,i+1):
    print(j,end=" ")
  print("")

# 10
# 1214
# 161820
# 22242628

count=10
for i in range(1,5):
  for i in range(1,i+1):
    print(count,end=" ")
    count+=2
  print("")

# ABC
# AB
# A

for i in range(1,4):
  c=65
  for j in range(3,i-1,-1):
    print(chr(c),end=" ")
    c+=1
  print("")

# ABCD
# EFG
# HI
# J

c=65
for i in range(1,5):
  for j in range(4,i-1,-1):
    print(chr(c),end=" ")
    c+=1
  print("")

#     *
#    **
#   ***
#  ****
# *****

for i in range(1,6):
  for j in range(i,5):
    print(" ",end=" ")
  for k in range(1,i+1):
    print('*',end=" ")
  print("")

