# -*- coding: utf-8 -*-
"""Day 2T.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztI4f-V2Y89qSHXdqNFHW0dZ7q8u0iC7
"""

# Conditonal Statement
# 3 variables --> min value out of the same

a=int(input("Enter the first value : "))
b=int(input("Enter the second value : "))
c=int(input("Enter the third value : "))
if a<b and a<c:
    print(f"The min value is {a}")
elif b<a and b<c:
    print(f"The min value is {b}")
elif c<a and c<b:
    print(f"The min value is {c}")
else:
    print("All are equal")6

# if variable is multiple of 2 and 6 print hi otherwise by
a=int(input("Enter the value :"))
if a%2==0 and a%6==0:
  print("Hi")
else:
  print("By")

# take a var name as age if age is greater then 10 print child
# if it is greater than 18 we will print adult
# if it is greater then 30 print mature
# if is is grater then 60 print old
# otheriwise print infant

age=int(input("Enter the age : "))
if age>10 and age<=18:
  print("child")
elif age>18 and age<=30:
  print("adult")
elif age>30 and age<=60:
  print("mature")
elif age>60:
  print("old")
else:
  print("infant")

# or

# hw reverse

# nested if-else

''' age>5 aadhar card created
age>18 adhar and pan linked '''

age=19
if(age>5):
  print("Adhar card created")
  if(age>18):
    print("Adhar and pan linked")
  else:
    print("Pan card not created")
else:
  print("Age is small")

# if a num is divisible by 2 print num is div by 2 and
# num is divisible 2 and 3 then print num is div by 6
# otherwise is not divisible by 2

num=int(input("Enter the num : "))
if num%2==0:
  print("num is div by 2")
  if num%3==0:
    print("num is div by 6")
  else:
    print("num is not div by 6")
else:
  print("num is not div by 2")

# learning assignment
# what is the diff btw python version 2 and version 3